// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PromoRepository is an autogenerated mock type for the PromoRepository type
type PromoRepository struct {
	mock.Mock
}

type mockConstructorTestingTNewPromoRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewPromoRepository creates a new instance of PromoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPromoRepository(t mockConstructorTestingTNewPromoRepository) *PromoRepository {
	mock := &PromoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
