// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SizeRepository is an autogenerated mock type for the SizeRepository type
type SizeRepository struct {
	mock.Mock
}

type mockConstructorTestingTNewSizeRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewSizeRepository creates a new instance of SizeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSizeRepository(t mockConstructorTestingTNewSizeRepository) *SizeRepository {
	mock := &SizeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
