// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UserPromoRepository is an autogenerated mock type for the UserPromoRepository type
type UserPromoRepository struct {
	mock.Mock
}

type mockConstructorTestingTNewUserPromoRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserPromoRepository creates a new instance of UserPromoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserPromoRepository(t mockConstructorTestingTNewUserPromoRepository) *UserPromoRepository {
	mock := &UserPromoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
